import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import {buildAuthorizedChatRoot} from '../../release-refinements.js';
const extension=process.env.ZENTRA_CHAT_ROOT || '/Users/cristiangatica/Downloads/IA/Zentra AI/ZENTRA FINALES/STAGING/ZENTRA_AI_CHROME_LAB_STAGING';
const codes=[readFileSync(extension+'/claude-chatbot.js','utf8'),readFileSync(new URL('../../trusted-chat-builders.js',import.meta.url),'utf8')];
const {JSDOM}=createRequire(import.meta.url)('jsdom');
function bot(code){
 const sandbox=vm.createContext({window:{},document:{addEventListener(){},getElementById(){return null;}},URL,URLSearchParams,console:{log(){},warn(){},error(){}}});
 new vm.Script(code).runInContext(sandbox);
 const b=Object.create(sandbox.window.ClaudeChatbot.prototype);
 Object.assign(b,{conversation:[],documentContexts:[],taskMemory:{},isContextLoaded:true,webContext:{url:'https://desk.example.test/ticket/1',title:'Ticket sintético',textContent:'Ticket visible'}});
 b.getPromptPersonalizationContext=async()=>null;b.loadSiteContextForChat=async()=>null;return b;
}
const urls=['https://example.test/coloracion','https://crm.example.test/ticket/1','https://example.test/portfolio'];
const completion='Se implementó el botón «Ver resultados reales» enlazado al portfolio. Se configuró el popup de reseñas a los 20 segundos y el CTA «Ver opiniones en Google». Los trabajos quedaron finalizados según tu confirmación.';
function classify(b,userMessage){const interactionMeta=b.detectInteractionMode({message:userMessage});const fastIntent=b.detectFastChatIntent(userMessage,null,interactionMeta);const taskIntent=b.detectTaskIntent(userMessage,null,interactionMeta);return {userMessage,interactionMeta,fastIntent,taskIntent,responseContract:b.detectResponseContract({userMessage,interactionMeta,fastIntent,taskIntent})};}
async function root(b,input){const args=classify(b,input);return buildAuthorizedChatRoot({messages:[{role:'user',content:input}]},{version:1,...args,state:{webContext:b.webContext,conversation:b.conversation,documentContexts:[],taskMemory:{},isContextLoaded:true}},{plan:'free',status:'active'});}
for(const reference of [urls[0],urls.join('\n'),'[Web]('+urls[0]+')\n\\[CRM\\]\\('+urls[1]+'\\)','Ticket:\n1. Agregar botón portfolio.\n2. Popup a los 20 segundos.\n3. CTA Google Reviews.\n'+urls.join('\n')])test('QA012 operational completion is not replaced by URL cleanup: '+reference.slice(0,35),async()=>{
 const input='Ya realicé los cambios solicitados. Dame la resolución final del caso.\n\nMaterial de referencia:\n'+reference;
 for(const code of codes){const b=bot(code);b.lastPromptBuildMeta={userMessage:input};assert.equal(classify(b,input).fastIntent.type,'case_resolution');assert.equal(b.resolvePastedUrlTaskForMessage(input),null);assert.equal(b.normalizeFinalAssistantOutput(completion),completion);
 const result=await root(b,input),system=result.body.messages.find(m=>m.role==='system').content;assert.doesNotMatch(system,/ORGANIZACION DE URLS|Páginas para revisar/);assert.ok(result.body.messages.some(m=>m.role==='user'&&m.content===input));assert.match(system,/resolucion/i);
 }
});
test('QA012 explicit page analysis survives multiple URLs without a forced cleanup fallback',async()=>{for(const code of codes){const b=bot(code),input='Analizá estas páginas y revisá su SEO:\n'+urls.join('\n');b.lastPromptBuildMeta={userMessage:input};assert.equal(b.resolvePastedUrlTaskForMessage(input),null);assert.equal(classify(b,input).responseContract.outputType,'diagnostic');const candidate='La estructura requiere revisar los títulos y la navegación. No se ejecutaron cambios.';assert.equal(b.normalizeFinalAssistantOutput(candidate),candidate);const result=await root(b,input);assert.match(result.body.messages.find(m=>m.role==='system').content,/REGLA ESPECIFICA PARA ANALISIS DE WEB/);}});
test('QA012 resolution follow-up does not inherit a prior multi-URL cleanup; explicit link list still works',()=>{for(const code of codes){const b=bot(code);b.conversation=[{type:'user',content:'Organizá estos links con comentarios:\n'+urls.join('\n')}];b.lastPromptBuildMeta={userMessage:'Dame la resolución final del caso'};assert.equal(b.resolvePastedUrlTaskForMessage(b.lastPromptBuildMeta.userMessage),null);assert.equal(b.normalizeFinalAssistantOutput(completion),completion);assert.equal(b.resolvePastedUrlTaskForMessage('Solo los links').linksOnly,true);const task=b.resolvePastedUrlTaskForMessage(b.conversation[0].content);assert.ok(task);assert.match(b.buildPastedUrlTaskFallback(task),/Páginas para revisar/);}});
test('QA012 URL cleanup parses escaped Markdown without Markdown inside the destination',()=>{for(const code of codes){const b=bot(code),input='Organizá estos links:\n[Web]('+urls[0]+')\n\\[CRM\\]\\('+urls[1]+'\\)';assert.deepEqual(Array.from(b.extractPastedUrlTaskEntries(input),e=>e.url),urls.slice(0,2));}});
test('QA012 inline Markdown links remain one safe anchor, including escaped/nested syntax',()=>{for(const code of codes){const b=bot(code);for(const input of ['[Web]('+urls[0]+'?a=1&b=2)', '\\[Web\\]\\('+urls[0]+'\\)', '[Web ['+urls[0]+']('+urls[0]+')]('+urls[0]+')']){const dom=new JSDOM(b.formatInlineText(input));const links=[...dom.window.document.querySelectorAll('a')];assert.ok(links.length>=1);assert.ok(links.every(a=>!/[\[\]\\]/.test(a.getAttribute('href'))));assert.equal(dom.window.document.querySelector('a a'),null);assert.ok(links[0].href.startsWith(urls[0]));dom.window.close();}assert.doesNotMatch(b.formatInlineText('<img src=x onerror=alert(1)> [bad](javascript:alert(1))'),/<img|href="javascript:/);}});
test('QA012 links retain query arrays, fragments, IPv6 and balanced URL parentheses',()=>{for(const code of codes){const b=bot(code);for(const url of ['https://example.test/path?item[]=1&item[]=2#section','http://[::1]/path','https://example.test/a_(b)?x=1#part']){for(const input of [url,'[Destino]('+url+')']){const dom=new JSDOM(b.formatInlineText(input));assert.equal(dom.window.document.querySelector('a')?.getAttribute('href'),url);dom.window.close();}assert.equal(b.extractPastedUrlTaskEntries(url)[0].url,url);}}});
const questions=['¿Qué requiere este cliente?','¿Qué es el CSR?','La web ya tiene SSL.','¿Qué debemos hacer si el hosting está en un proveedor externo?'];
for(const input of questions)test('QA010 non-identity question cannot be replaced by identity reply: '+input,()=>{for(const code of codes){const b=bot(code);b.lastPromptBuildMeta={userMessage:input};assert.equal(b.isModelDisclosureRequest(input),false);const candidate='Respuesta sintética pertinente a la consulta actual.';assert.equal(b.normalizeFinalAssistantOutput(candidate),candidate);assert.equal(b.resolveAssistantTextFromData({success:true,response:candidate},{userMessage:input}),candidate);}});
test('QA010 direct identity requests keep their existing response',()=>{for(const code of codes){const b=bot(code);for(const input of ['¿Qué modelo usás?','¿Sos ChatGPT?','¿Qué tecnología usa Zentra?']){b.lastPromptBuildMeta={userMessage:input};assert.equal(b.isModelDisclosureRequest(input),true);assert.equal(b.normalizeFinalAssistantOutput('Respuesta del modelo'),b.getPublicAssistantIdentityReply());}}});
test('QA010 explicit current request wins over stale identity build metadata',()=>{for(const code of codes){const b=bot(code);b.lastPromptBuildMeta={userMessage:'¿Qué modelo usás?'};const candidate='Un CSR es una solicitud de firma de certificado, no un certificado SSL instalado.';for(const response of [candidate,{response:candidate},JSON.stringify({response:candidate})])assert.equal(b.resolveAssistantTextFromData({success:true,response},{userMessage:'¿Qué es el CSR?'}),candidate);assert.equal(b.lastPromptBuildMeta.userMessage,'¿Qué modelo usás?');}});
test('QA010 empty/error output cannot become a successful identity reply',()=>{for(const code of codes){const b=bot(code);for(const input of [...questions,'¿Qué modelo usás?']){b.lastPromptBuildMeta={userMessage:input};assert.notEqual(b.normalizeFinalAssistantOutput(''),b.getPublicAssistantIdentityReply());assert.notEqual(b.normalizeFinalAssistantOutput('Error: servidor no disponible'),b.getPublicAssistantIdentityReply());assert.notEqual(b.sanitizePublicAssistantOutput('Error: servidor no disponible'),b.getPublicAssistantIdentityReply());assert.throws(()=>b.resolveAssistantTextFromData({success:false,error:'OFFLINE_ERROR'},{userMessage:input}),/OFFLINE_ERROR/);assert.equal(b.resolveAssistantTextFromData({success:true,response:'Respuesta recuperada válida.'},{userMessage:questions[0]}).length>0,true);}}});
